### ISSUE TITLE
Sharp as peer dependency

### ISSUE THREAD

**Issue by sapkra** [fiahfy/icns-convert#2]
I'm using `sharp` additionally to `icns-convert` to generate my icons. After updating sharp to the latest version it broke because this library is using an older version. This results in a incompatibility.
See https://github.com/lovell/sharp/issues/2029#issuecomment-576058931

I think it would be helpful to have sharp as a peer dependency so that there will be just one sharp version installed.

**Comment by fiahfy** [comment]
Thanks, I will see to it.

**Comment by fiahfy** [comment]
I tried to reproduce the phenomenon by the following steps, but I couldn't.
```
$ node -v
v12.3.1
$ yarn -v
1.21.1
$ yarn init
$ yarn add sharp @fiahfy/icns-convert
$ cat package.json 
{
  "name": "reproduced-project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@fiahfy/icns-convert": "^0.0.8",
    "sharp": "^0.24.0"
  }
}
$ grep version node_modules/sharp/package.json 
  "version": "0.24.0",
$ grep version node_modules/@fiahfy/icns-convert/node_modules/sharp/package.json 
  "version": "0.23.4",
$ ./node_modules/.bin/icns-convert
```
Can you show the reproduction procedure or sample project?

**Comment by sapkra** [comment]
Thank you for looking into it.
Here you can find my example repository: https://github.com/sapkra/sharp-issue-2029

**Comment by sapkra** [comment]
The guys at sharp are also looking into it to find a general solution. I think this problem should not be solved by all libraries they are using sharp. Closing it.
https://github.com/lovell/sharp/issues/2046
